/// <reference types="@cloudflare/workers-types" />
/**
 * Custom Cloudflare Workers entry (Engineer A, Phase 4) — `main` in wrangler.jsonc.
 *
 * WHY THIS EXISTS:
 *   We migrated off legacy Cloudflare Pages → Workers Static-Assets mode so the
 *   deploy can run Cron Triggers + a Queue consumer (Pages supports NEITHER).
 *   `@sveltejs/adapter-cloudflare` generates the SSR worker but exports ONLY a
 *   `fetch` handler — it has no hook to add `scheduled`/`queue`. So this thin entry:
 *     1. imports the adapter-generated worker (its `fetch`),
 *     2. re-exports that `fetch` UNCHANGED (all HTTP → SvelteKit → Hono, as before),
 *     3. adds `scheduled` (cron) and `queue` (consumer) handlers.
 *
 *   No adapter fork. The adapter builds against `wrangler.adapter.jsonc` (which has
 *   NO `main`) and emits `.svelte-kit/cloudflare/_worker.js`; this file imports it.
 *   That generated file only exists AFTER `vite build`, so the import is typed via an
 *   ambient declaration (see src/worker-generated.d.ts) to keep `svelte-check` green
 *   pre-build.
 *
 * BUSINESS LOGIC LIVES IN SEAMS (Engineer F owns the bodies):
 *   - scheduled → src/lib/server/jobs/scheduled.ts  → handleScheduled
 *   - queue     → src/lib/server/jobs/queue.ts       → handleQueue
 *   This entry only does wiring; it implements no rank-track / shop-analysis logic.
 */
// Generated by `@sveltejs/adapter-cloudflare` at build time (resolves after `vite build`,
// path = `main` in wrangler.adapter.jsonc); typed pre-build via the ambient declaration
// in src/worker-generated.d.ts.
import sveltekitWorker from '../.svelte-kit/server-worker/index.js';
import { handleScheduled } from '$lib/server/jobs/scheduled';
import { handleQueue } from '$lib/server/jobs/queue';
import { handleDLQ } from '$lib/server/jobs/dlq';
import type { Env } from '$lib/server/env';
import type { AnalysisQueueMessage } from '$lib/server/jobs/types';

export default {
  /**
   * ALL HTTP delegates to the SvelteKit-generated worker (Static Assets + SSR +
   * the Hono app mounted at /api/*). Unchanged from the adapter's behaviour.
   */
  fetch(request: Request, env: Env, ctx: ExecutionContext): Response | Promise<Response> {
    return sveltekitWorker.fetch(request, env, ctx);
  },

  /**
   * Cron Triggers (wrangler.jsonc → triggers.crons). Dispatch is decided inside
   * handleScheduled by branching on `event.cron`. Errors must be caught there;
   * we guard here too so a job failure never surfaces as an unhandled rejection.
   */
  async scheduled(event: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    try {
      await handleScheduled(event, env, ctx);
    } catch (err) {
      console.error(`[worker.scheduled] cron="${event.cron}" failed:`, err);
    }
  },

  /**
   * Queue consumer (wrangler.jsonc → queues.consumers).
   *
   * Routes by queue name:
   *   - "herorank-analysis"     → handleQueue (main consumer, ack/retry per-message)
   *   - "herorank-analysis-dlq" → handleDLQ   (DLQ consumer, always ack, mark job failed)
   *
   * A throw here would retry the ENTIRE batch; we let the handlers own per-message
   * control and only guard here as a last-resort backstop.
   */
  async queue(
    batch: MessageBatch<AnalysisQueueMessage>,
    env: Env,
    ctx: ExecutionContext
  ): Promise<void> {
    try {
      if (batch.queue === 'herorank-analysis-dlq') {
        await handleDLQ(batch, env, ctx);
      } else {
        await handleQueue(batch, env, ctx);
      }
    } catch (err) {
      console.error(`[worker.queue] queue="${batch.queue}" batch failed:`, err);
    }
  }
} satisfies ExportedHandler<Env, AnalysisQueueMessage>;
